server:
  port: 3003
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db이름
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 비밀번호
    initialization-mode: always
    continue-on-error: true
    
    
servlet:
  multipart:
    enabled: true
    file-size-threshold: 1MB
    location: C:/Temp
    max-file-size: 100MB
    max-request-size: 100MB    

mybatis:
 mapper-locations: classpath:mapper/**/*.xml
 type-aliases-package: com.dictation.vo